### ISSUE TITLE
Range of integer values

### ISSUE THREAD

**Issue by chiphuyen** [NVIDIA/Milano#4]
Right now, you can specify params either as discrete values or continuous values (range). It'd be nice to be able to specify that a param is within a range but only takes integer values.

For example, if I specify:

"--nhid": {
			"type": "integer_range", "min": 100, "max": 400
		},

It'll only search for integer values between 100 and 400, inclusive.

Thanks!

**Comment by Kipok** [comment]
I think you should be able to easily do that with the "values" type. Since the configuration file is just a Python file, you can always write something like this:

```Python
"--nhid": {
    "type": "values", "values": list(range(100, 401)),
}
```

You can even specify non-consecutive ranges with similar tricks if need to. There might be some overhead from constructing this list explicitly, but only when you need to search really large spaces (like integers from 1 to 10^7), which does not seem to be the usual case in practice.

**Comment by chiphuyen** [comment]
Oooh that's smart. Thanks a lot!
